name: Run Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.2
            laravel: 10.*
            os: ubuntu-latest
            framework: "^10.0"
            testbench: "^8.0"
          - php: 8.3
            laravel: 11.*
            os: ubuntu-latest
            framework: "^11.0"
            testbench: "^9.0"
          - php: 8.4
            laravel: 12.*
            os: ubuntu-latest
            framework: "^12.0"
            testbench: "^10.0"

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            config
            resources/lang
            resources/views
            src
            tests
            composer.json
            phpunit.xml.dist
            .github/workflows/tests.yml
            **.php

      - name: Determine whether tests should run
        id: should-run-tests
        if: steps.changed-files.outputs.any_modified == 'true' || github.event_name == 'schedule'
        run: echo "result=true" >> $GITHUB_OUTPUT

      - name: Update apt sources
        if: steps.should-run-tests.outputs.result == 'true'
        run: |
          sudo apt-get check || sudo apt --fix-broken install -y
          sudo apt-get update

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.framework }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
