name: Run Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.4
            laravel: 12.*
            statamic: 5.*
            os: ubuntu-latest
            framework: "^12.0"
            testbench: "^10.0"
          - php: 8.4
            laravel: 12.*
            statamic: 6.*
            os: ubuntu-latest
            framework: "^12.0"
            testbench: "^10.0"
          - php: 8.5
            laravel: 13.*
            statamic: 6.*
            os: ubuntu-latest
            framework: "^13.0"
            testbench: "^11.0"

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - S${{ matrix.statamic }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@cf4cade2721090509697bbedc2ee0eef765b62bc # v2.34.1
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.composer/cache/files
          key: composer-${{ matrix.php }}-${{ matrix.laravel }}-${{ matrix.statamic }}-${{ hashFiles('composer.json') }}
          restore-keys: |
            composer-${{ matrix.php }}-${{ matrix.laravel }}-${{ matrix.statamic }}-

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.framework }}" "statamic/cms:${{ matrix.statamic }}" --no-interaction --no-update
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          composer update --prefer-dist --no-interaction -W

      - name: Execute tests
        run: vendor/bin/phpunit
